swipe:
    3:
        down:
            command: "ydotool key 29:1 15:1 15:0 29:0"
        up:
            command: "ydotool key 29:1 42:1 15:1 15:0 42:0 29:0"
pinch:
    3:
        out:
            end:
                command: "ydotool key 29:1 17:1 17:0 29:0"
        in:
            end:
                command: "ydotool key 29:1 20:1 20:0 29:0"
hold:
    4:
        end:
            command: "ydotool key 29:1 32:1 32:0 29:0"
