[options]
  colorscheme = "tokyonight"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  vim_help_language = "cn"
  autocomplete_method = "coc"
  lint_engine = "ale"
  bootstrap_before = "bootstrap#before"
  bootstrap_after = "bootstrap#after"

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "ui"
  enable_cursorword = true

[[layers]]
  name = 'shell'
  default_position = 'float'
  default_height = 30

[[layers]]
  name = 'git'

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = "treesitter"

[[layers]]
  name = "denite"

[[layers]]
  name = "chinese"

# [[layers]]
  # name = "format"
  # format_on_save = true

[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#html"
  emmet_filetypes = ["html","vue"]

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"
  enabled_formatter = "prettier"

[[layers]]
  name = "lang#rust"
  recommend_style = true

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lsp"
  filetypes = ["rust"]
  [layers.override_cmd]
    rust = ["rust-analyzer"]

[[custom_plugins]]
  repo = "folke/tokyonight.nvim"
  merged = 0
